### ISSUE TITLE
Maps listed as Variants

### ISSUE THREAD

**Issue by jcooke92** [Swiggies/PressJsonToJson#1]
Maps are incorrectly being classified as variants. The map in this picture is "LandSharks" which shows up as a variant. The variant is actually "Shark Attack",
![untitled](https://user-images.githubusercontent.com/17241834/39394359-074f29a0-4a97-11e8-8ed8-6f4d0c05a16b.png)
![untitled1](https://user-images.githubusercontent.com/17241834/39394361-0fde5492-4a97-11e8-8639-68d63e661e3a.png)

**Comment by Swiggies** [comment]
Could I see your variants folder? In the image you showed, you have the folder listed as "LandSharks" but "LandShark" in the program which leads me to believe you may have a "LandShark" variant.

**Comment by jcooke92** [comment]
You're right. I quickly scanned through my variants folder and didn't see the LandShark variant. Deleted it and all is well.
